[package]
name = "heptagon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.11.0"
env_logger = "0.9.0"
log = "0.4.16"
wgpu = "0.12.0"
winit = "0.26.1"
